### ISSUE TITLE
Przeniesienie wywołania wow.js

### ISSUE THREAD

**Issue by klojniewski** [Szalkowski/one-page-project#10]
`<script>
            new WOW().init();
        </script>`

Trzeba przenieść do main.js.

Main.js służy do wywoływania wszystkich skryptów jakie masz na stronie.

**Comment by Szalkowski** [comment]
poprawiłem już. a tak ogólnie to jak mnie oceniasz?

Pozdrawiam
Maciej Szałkowski

2016-04-12 22:00 GMT+02:00 Krzysztof Łojniewski notifications@github.com:
