### ISSUE TITLE
Stylowanie po elementach

### ISSUE THREAD

**Issue by klojniewski** [Szalkowski/one-page-project#2]
W ostatnim projekcie, mówiłem Ci, żeby unikać stylowania po elementach.
np. 

`.head {background: #000}`

Dlatego dodawaj classy, np. tutaj:

`<header>`

Pamiętasz dlaczego prosiłem o nie stylowanie po elementach?

**Comment by Szalkowski** [comment]
dlatego ze moga byc dwa rozne headery w projekcie.

Pozdrawiam
Maciej Szałkowski

2016-04-12 21:46 GMT+02:00 Krzysztof Łojniewski notifications@github.com:
