### ISSUE TITLE
Zauważyłem, że często udaje Ci się używać class w wielu miejsach a przez to mniej powtarzać kod

### ISSUE THREAD

**Issue by klojniewski** [Szalkowski/one-page-project#6]
Fajnie, że zacząłeś to wprowadzać do życia. Widzisz tego zasadność?

**Comment by Szalkowski** [comment]
ma to sens jeżeli strona jest co jakiś czas zmieniana lub są dodawane
kolejne komponenty a tak pewnie się często zdarza w zawodowej pracy

Pozdrawiam
Maciej Szałkowski

2016-04-12 21:54 GMT+02:00 Krzysztof Łojniewski notifications@github.com:
